server:
  port: 8080   # Gateway s? l?ng nghe ? c?ng 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
#      routes:
#        - id: user-service
#          uri: http://localhost:8081        # service user ch?y c?ng 8081
#          predicates:
#            - Path=/users/**
